---
title: "Chap 2 - Hood vs. Bench"
author: "Linh Dang"
editor: visual
execute:
  warning: false
  message: false
format:
  html:
    code-fold: true
    toc: true
    toc-location: left
    toc-depth: 3
---

```{r message=FALSE}
library(phyloseq)
library(microbiome)
library(vegan)
library(rstatix)
library(ggpubr)
library(Wrench)
library(tidyverse)

rm(list = ls())
pseq <- readRDS("../../../data/Chap2/px_J_U_NCT_v02_taxfilter.rds")
```

# Project Description

Investigate NCT samples in different environments: as normal (bench), and clean (Hood).

Common variables and functions

```{r echo=TRUE}
Kolors <- c("#9d547c","#56ca63","#a357d6","cornflowerblue","#419d2a","sandybrown","red3","peachpuff","cyan","paleturquoise3","mistyrose","mediumpurple","mediumseagreen","mediumorchid","moccasin","orange4","olivedrab","midnightblue","papayawhip","palevioletred4","brown1","greenyellow","orchid","navy","darkred","navajowhite1","mistyrose1","grey85","#525fd6","red2","#8cbe3a","#c944aa","indianred3","#5ba557","#9e66cb","#c1b735","#6d82ec","grey25","#e69728","#6654b0","lightsalmon3","lightcyan1","khaki1","seagreen1","plum1","lightsteelblue1","palevioletred3","mintcream","magenta3","#799330","#da7fdf","#3c782c","#e44586","blue4","#63c996","#dc3f53","#49cbc8","#cf3f29","#4fabda","#da6c2b","#598bd1","#b78c24","#8d4191","#a0b971","slategray1","sienna","plum1","lightyellow1","lightskyblue3","linen","limegreen","cornsilk1","mediumaquamarine","gray14","gold3","darkviolet","#b2386a","#479d71","#ae4341","#2ba198","#e07557","#5361a3","#dda353","#aa98df","#5b6114","#dc89bf","#327243","slateblue1","#e57b94","#277257","#9b62a0","#bbab59","#98495a","#526229","#d8827d","#857624","gray40","#9a4a22","#7c7d46","mediumslateblue","lemonchiffon1","#e3a073","#9e6b33", "gray74","slateblue1","rosybrown3", "lawngreen","gainsboro","dodgerblue3","deeppink3","firebrick3", "orchid2", "olivedrab1", "ivory3", "darkseagreen", "bisque2", "darkgoldenrod2", "blue2", "skyblue", "seashell2", "turquoise", "tan1", "seagreen2", "palevioletred3", "linen", "steelblue4","ghostwhite","dodgerblue1","deeppink1","firebrick1", "limegreen", "purple3", "khaki3", "snow3", "darkslategray","darkorchid","lavender", "magenta2", "palegreen", "salmon", "maroon", "cyan2","#671408","#FAEBD7","#7FFFD4","#F0FFFF","#A52A2A","burlywood","cadetblue","#7FFF00","chocolate","cornsilk","slateblue1","#FF7F50","red1","#008B8B","darkgoldenrod1","darkolivegreen","darkorange4","white","hotpink","honeydew1","goldenrod2","darkgreen","oldlace","darkslategray3","navajowhite3","orchid4","gray25","#F0924D")

## Alpha analysis
AlphaPlot_Violin <- function(PhyloObj, index = "Observed", strata = "treatment", y_label = "Observed species", add_legend = FALSE, m_paired = F, gg_title = NULL){
  #group.colors <- c(ctrl = "dodgerblue3", Gem = "firebrick2")
  condition_names <- sample_data(PhyloObj)[[strata]] %>% table() %>% names()
  group.colors <- Kolors[1:length(condition_names)]
  names(group.colors) <- condition_names
  #my.labels <- c("Ctrl", "Gem")
  my.labels <- condition_names
  tmp2 <- PhyloObj %>% estimate_richness()
  # new_names <- rownames(tmp2) %>% 
  #   gsub("^X", "", .) %>% 
  #   gsub("\\.", "-", .)
  # rownames(tmp2) <- new_names
  rich_meta <- merge(PhyloObj %>% sample_data(), tmp2, by = "row.names")
  ##-- only using statistics test
  ob <- rich_meta %>% t_test(as.formula(paste0(index, " ~ ", strata)), paired = m_paired) %>% adjust_pvalue(method = "BH") %>%  add_significance("p.adj") %>% add_xy_position()
  
  p1 <- ggplot (rich_meta, aes(x = !!sym(strata), y = !!sym(index), fill=!!sym(strata)))+ 
    #geom_boxplot()+
    geom_violin() +
    geom_boxplot(width=0.2) +
    geom_point (position=position_jitterdodge( jitter.width = 0.05))+
    theme_gray() + 
    scale_x_discrete(labels= my.labels)+
    #xlab(strata)+
    ylab(y_label)+
    # facet_grid(.~tp)+
    #scale_x_discrete(labels= my.labels)+
    scale_fill_manual(values=group.colors, labels = my.labels)+
    ggtitle(gg_title) +
    #ggtitle("KPC tumor vs. Healthy pancreas - Observed species") +
    theme(axis.text.y = element_text (size=11),
          axis.title = element_text(size=12, face="bold"))
  
  if(!add_legend){    
    p1 <- p1 + theme(legend.position = "none",
                     # legend.background = element_rect(size=0.25, linetype="solid", colour ="black"),
                     legend.key.size = unit(4,"mm"),
                     #axis.text.x = element_blank(),
                     plot.title = element_text(size = 12))
    
  } else {
    p1 <- p1 + theme(legend.text = element_text(size = 12),
                     #legend.title = element_blank(),
                     # legend.background = element_rect(size=0.25, linetype="solid", colour ="black"),
                     legend.key.size = unit(4,"mm"),
                     axis.text.x = element_blank(),
                     plot.title = element_text(size = 12))
  }
  p1 <- p1 + stat_pvalue_manual(ob, label = "p.adj", inherit.aes = FALSE, tip.length = 0.01)
  return(p1)
}
## Wrench Normalization
WrenchWrapper <- function(PhyloObjct, grp, roundUp = F){
  cnt_table <- PhyloObjct %>% otu_table()
  group <- PhyloObjct %>% sample_data() %>% pull(grp)
  w <- wrench(cnt_table, condition = group)
  
  # deseq.obj <- DESeqDataSetFromMatrix(cnt_table %>% as.data.frame(), DataFrame(group), ~group)
  # DESeq2::sizeFactors(deseq.obj) <- w$nf
  # cnt_table_normalized <- DESeq2::counts(deseq.obj, normalized=TRUE)
  
  norm_factors <- w$nf
  norm_counts <- sweep(cnt_table, 2, norm_factors, FUN = '/')
  if(roundUp){norm_counts <- norm_counts %>% round()}
  if(!is.null(phy_tree(PhyloObjct, errorIfNULL = F))){
    return(phyloseq(otu_table(norm_counts, taxa_are_rows = T), tax_table(PhyloObjct %>% tax_table()), sample_data(PhyloObjct %>% sample_data()),
                    phy_tree(PhyloObjct)))
  } else{
    return(phyloseq(otu_table(norm_counts, taxa_are_rows = T), tax_table(PhyloObjct %>% tax_table()), sample_data(PhyloObjct %>% sample_data())))
  }
}
```

# Basic Analysis

## Alpha Diversity

```{r}

```

## Beta Diversity

# DAA
